
var xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n    <!DOCTYPE score-partwise PUBLIC\n        \"-//Recordare//DTD MusicXML 3.1 Partwise//EN\"\n        \"http://www.musicxml.org/dtds/partwise.dtd\">\n    <score-partwise version=\"3.1\">\n        <work>\n          <work-title>Generated Score</work-title>\n        </work>\n        <identification>\n          <encoding>\n            <encoding-date>2018-10-13</encoding-date>\n            <software>Muziq Web</software>\n          </encoding>\n        </identification>\n        <part-list>\n          <score-part id=\"P1\">\n            <part-name>Piano</part-name>\n          </score-part>\n            <measure number=\"1\">\n      <attributes>\n        <divisions>2</divisions>\n      </attributes>\n      <note>\n          <pitch>\n      <step>E</step>\n      <octave>1</octave>\n      \n  </pitch>\n          <duration>8</duration>\n          <type>whole</duration>\n      </note>\n  </measure>\n  <measure number=\"2\">\n      <attributes>\n        <divisions>2</divisions>\n      </attributes>\n      <note>\n          <pitch>\n      <step>F</step>\n      <octave>1</octave>\n      <alter>1</alter>\n  </pitch>\n          <duration>8</duration>\n          <type>whole</duration>\n      </note>\n  </measure>\n  <measure number=\"3\">\n      <attributes>\n        <divisions>2</divisions>\n      </attributes>\n      <note>\n          <pitch>\n      <step>G</step>\n      <octave>1</octave>\n      <alter>1</alter>\n  </pitch>\n          <duration>8</duration>\n          <type>whole</duration>\n      </note>\n  </measure>\n  <measure number=\"4\">\n      <attributes>\n        <divisions>2</divisions>\n      </attributes>\n      <note>\n          <pitch>\n      <step>E</step>\n      <octave>1</octave>\n      \n  </pitch>\n          <duration>8</duration>\n          <type>whole</duration>\n      </note>\n  </measure>\n  <measure number=\"5\">\n      <attributes>\n        <divisions>2</divisions>\n      </attributes>\n      <note>\n          <pitch>\n      <step>G</step>\n      <octave>1</octave>\n      <alter>1</alter>\n  </pitch>\n          <duration>8</duration>\n          <type>whole</duration>\n      </note>\n  </measure>\n  <measure number=\"6\">\n      <attributes>\n        <divisions>2</divisions>\n      </attributes>\n      <note>\n          <pitch>\n      <step>F</step>\n      <octave>1</octave>\n      <alter>1</alter>\n  </pitch>\n          <duration>8</duration>\n          <type>whole</duration>\n      </note>\n  </measure>\n        </part-list>\n    </score-partwise>";

var codeDisplay = document.getElementById("xml-display");
codeDisplay.innerText = window.formatXML(xml);

hljs.highlightBlock(codeDisplay);

var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("container");

osmd.load(xml)
    .then(
        () => osmd.render()
    );
        